# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Opendata
email: kandimalla.sreeram@gmail.com
description: |
  Opendata India, Local Government Directory
baseurl: "/opendata" # the subpath of your site, e.g. /blog
url: "https://ramseraph.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ramSeraph
github_username:  ramSeraph
github: [metadata]

# Build settings
markdown: kramdown
#remote-theme: syaning/slim
remote-theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-remote-theme

header_pages:
  - index.md
  - about.md

style: hacker # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

#footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'

#google_analytics: UA-NNNNNNNN-N

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
